version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: edurank-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: edurank
    ports:
      - "5432:5432"
    volumes:
      - edurank_data:/var/lib/postgresql/data

volumes:
  edurank_data:
    