version: "3.9"

services:
  db:
    image: postgres:16
    container_name: my_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./edurank_fixed.sql:/docker-entrypoint-initdb.d/edurank.sql

volumes:
  db_data: